### User Registration
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "user1",
    "email": "user1@example.com",
    "password": "password"
}

### User Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user1@example.com",
    "password": "password"
}
