### User Registration
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "user1",
    "email": "user1@example.com",
    "password": "password"
}

### User Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user1@example.com",
    "password": "password"
}

### User Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJkZjhhZGNjLTc3NjQtNDRkZC05MDMxLThiZThlNGY4NTZmYiIsImVtYWlsIjoidXNlcjFAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mjc1OTE2MTgsImV4cCI6MTcyNzU5NTIxOH0.C3NSSS9BP6hcNSk7GPoSEmH6v4DKCj1_GRYOdCWmv1I

{
    "email": "user1@example.com"
}

### Create a new job
POST http://localhost:3000/jobs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJkZjhhZGNjLTc3NjQtNDRkZC05MDMxLThiZThlNGY4NTZmYiIsImVtYWlsIjoidXNlcjFAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mjc1OTE2MTgsImV4cCI6MTcyNzU5NTIxOH0.C3NSSS9BP6hcNSk7GPoSEmH6v4DKCj1_GRYOdCWmv1I

{
    "title": "Job 1",
    "description": "Job 1 description",
    "isActive": true,
    "command": "console.log('Hello World!');",
    "type": "once",
    "minute": 0,
    "hour": 0,
    "dayOfMonth": 1,
    "month": 1,
    "dayOfWeek": 1,
    "timezoneOffsetMinutes": -330,
    "startTime": "2021-07-20T00:00:00.000Z",
    "endTime": "2021-07-20T00:00:00.000Z",
    "retries": 3
}